// Code generated by "stringer -type EastAsianWidth -trimprefix EAW_"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EAW_W-0]
	_ = x[EAW_F-1]
	_ = x[EAW_A-2]
	_ = x[EAW_N-3]
	_ = x[EAW_Na-4]
	_ = x[EAW_H-5]
}

const _EastAsianWidth_name = "WFANNaH"

var _EastAsianWidth_index = [...]uint8{0, 1, 2, 3, 4, 6, 7}

func (i EastAsianWidth) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EastAsianWidth_index)-1 {
		return "EastAsianWidth(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EastAsianWidth_name[_EastAsianWidth_index[idx]:_EastAsianWidth_index[idx+1]]
}
