// Code generated by "stringer -type GeneralCategory -trimprefix CAT_"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CAT_Lu-0]
	_ = x[CAT_Ll-1]
	_ = x[CAT_Lt-2]
	_ = x[CAT_Lm-3]
	_ = x[CAT_Lo-4]
	_ = x[CAT_Mn-5]
	_ = x[CAT_Mc-6]
	_ = x[CAT_Me-7]
	_ = x[CAT_Nd-8]
	_ = x[CAT_Nl-9]
	_ = x[CAT_No-10]
	_ = x[CAT_Sm-11]
	_ = x[CAT_Sc-12]
	_ = x[CAT_Sk-13]
	_ = x[CAT_So-14]
	_ = x[CAT_Pc-15]
	_ = x[CAT_Pd-16]
	_ = x[CAT_Ps-17]
	_ = x[CAT_Pe-18]
	_ = x[CAT_Pi-19]
	_ = x[CAT_Pf-20]
	_ = x[CAT_Po-21]
	_ = x[CAT_Zs-22]
	_ = x[CAT_Zl-23]
	_ = x[CAT_Zp-24]
	_ = x[CAT_Cc-25]
	_ = x[CAT_Cf-26]
	_ = x[CAT_Cs-27]
	_ = x[CAT_Co-28]
	_ = x[CAT_Cn-29]
}

const _GeneralCategory_name = "LuLlLtLmLoMnMcMeNdNlNoSmScSkSoPcPdPsPePiPfPoZsZlZpCcCfCsCoCn"

var _GeneralCategory_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60}

func (i GeneralCategory) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GeneralCategory_index)-1 {
		return "GeneralCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GeneralCategory_name[_GeneralCategory_index[idx]:_GeneralCategory_index[idx+1]]
}
