// Code generated by "stringer -type TokenKind -trimprefix Token -linecomment"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOS-0]
	_ = x[TokenId-1]
	_ = x[TokenRune-2]
	_ = x[TokenColon-3]
	_ = x[TokenComma-4]
	_ = x[TokenLParen-5]
	_ = x[TokenRParen-6]
	_ = x[TokenNegate-7]
	_ = x[TokenPlus-8]
	_ = x[TokenMinus-9]
	_ = x[TokenMul-10]
	_ = x[TokenAt-11]
	_ = x[TokenRange-12]
	_ = x[TokenSpace-13]
}

const _TokenKind_name = "EOSidentifiercodePoint:,()!+-*@..space"

var _TokenKind_index = [...]uint8{0, 3, 13, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 38}

func (i TokenKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
